### ISSUE TITLE
Fehler Im Code

### ISSUE THREAD

**Issue by DavidImmanuelSchwieder** [AlexanderLPB/DevOps#3]
![image](https://github.com/AlexanderLPB/DevOps/assets/145438444/88ae15bf-6301-4d09-a83d-676188b7cd1e)
in diesem code sieht man, das du statt dev.json, main.json verwendet hast. Dadurch hat die function das gleiche ergebnis wie DeployTestToMain, deshalb entweder die function löschen oder einfach abändern

**Comment by AlexanderLPB** [comment]
Sehr geehrter Herr Schwieder,

Leider ist ihre Fehlerangabe sehr ungenau. Auf dem Screenshot ist nur eine Zeile Code lesbar, also weiß nicht nicht sicher ob das von ihnen beschriebene Problem vorhanden ist. Ich bitte Sie daher, nochmal eine ausführlichere Fehlerbeschreibung abzugeben mit einem passenden Screenshot. Ich bitte um ihr Verständnis.

LG. Alexander von Lindel.

**Comment by DavidImmanuelSchwieder** [comment]
Mein Problem bezieht sich auf ihre UserStory/two_three und dort um die datei deployTest.ps 

![image](https://github.com/AlexanderLPB/DevOps/assets/145438444/ceb0d460-dd5b-4e26-ac53-fd7c4fd9bdf8)
es handelt sich um die zeile 7 in dieser Datei bitte beheben sie das oben genannte problem 

LG. David von Schwieder

**Comment by AlexanderLPB** [comment]
Das Problem wurde behoben. Danke für ihr großartiges Feedback Herr Schieder, auf gute zukünftige Zusammenarbeit =)

LG. Elalex
